[tox]
env_list = lint, tests, examples

[testenv:lint]
deps = ruff
commands =
    ruff format --check src/ tests/
    ruff check src/ tests/

[testenv:format]
deps = ruff
commands =
    ruff format src/ tests/
    ruff check --fix src/ tests/

[testenv:tests]
extras = dev
commands =
    python -m pytest tests/ -v --override-ini="addopts="

[testenv:examples]
commands =
    bash -c "cd examples/md-ipi && bash run.sh"
